UploadDownloadFileMVC1/Models/ErrorViewModel.cs
namespace UploadDownloadFileMVC1.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

UploadDownloadFileMVC1/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace UploadDownloadFileMVC1.Controllers
{
    public class FileUploadController : Controller
    {
        public IActionResult Index()
        {
            var items = GetFiles();
            return View(items);
        }

        [HttpPost]
        public IActionResult Index(IFormFile file)
        {
            if (file != null && file.Length > 0)
            {
                try
                {
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UploadedFiles", file.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }

                    ViewBag.Message = "File uploaded successfully";
                }
                catch (Exception error)
                {
                    ViewBag.Message = "ERROR: " + error.Message.ToString();
                }
            }
            else
            {
                ViewBag.Message = "You have not specified a file.";
            }

            var items = GetFiles();
            return View(items);
        }

        public IActionResult Download(string ImageName)
        {
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UploadedFiles", ImageName);
            return PhysicalFile(filePath, "application/force-download", Path.GetFileName(filePath));
        }

        private List<string> GetFiles()
        {
            var dir = new DirectoryInfo(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UploadedFiles"));
            var fileNames = dir.GetFiles("*.pdf");

            var items = new List<string>();

            foreach (var file in fileNames)
            {
                items.Add(file.Name);
            }

            return items;
        }
    }
}

UploadDownloadFileMVC1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using UploadDownloadFileMVC1.Models;

namespace UploadDownloadFileMVC1.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

UploadDownloadFileMVC1/Views/FileUpload/Index.cshtml
@model List<string>
@{
    ViewBag.Title = "Index";
}
<h2>Upload File</h2>

<form action="@Url.Action("Index", "FileUpload")" method="post" enctype="multipart/form-data">
    <label for="file">Upload File:</label>
    <br>
    <input type="file" name="file" id="file" />
    <br>
    <br>
    <input type="submit" value="Upload File" />

    <br>
    @ViewBag.Message
    <br>

    <h3>Document</h3>
    <table>
        <tr>
            <th>File Name</th>
            <th>Download</th>
        </tr>

        @for (var i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@Model[i].ToString()</td>
                <td>@Html.ActionLink("Download", "Download", new { ImageName = @Model[i].ToString() })</td>
            </tr>
        }
    </table>
</form>

UploadDownloadFileMVC1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Try Upload And Download File</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UploadDownloadFileMVC1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UploadDownloadFileMVC1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UploadDownloadFileMVC1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UploadDownloadFileMVC1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UploadDownloadFileMVC1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>